-- Which class of products have been shipped highest(Quantity) to countries outside India other than USA

SELECT
	PRODUCT_CLASS_DESC,
    SUM(TOTAL_QUANTITY),
    SUM(TOTAL_VALUE)
FROM
	(SELECT
		PRODUCT_CLASS_DESC,
		SUM(PRODUCT_QUANTITY) AS TOTAL_QUANTITY,
		PRODUCT_QUANTITY * PRODUCT_PRICE AS TOTAL_VALUE
	 FROM
		ONLINE_CUSTOMER AS OC
		JOIN ADDRESS AS AD ON AD.ADDRESS_ID = OC.ADDRESS_ID
		JOIN ORDER_HEADER AS OH ON OH.CUSTOMER_ID = OC.CUSTOMER_ID
		JOIN ORDER_ITEMS AS OI ON OI.ORDER_ID = OH.ORDER_ID
		JOIN PRODUCT AS P ON P.PRODUCT_ID = OI.PRODUCT_ID
		JOIN PRODUCT_CLASS AS PC ON PC.PRODUCT_CLASS_CODE = P.PRODUCT_CLASS_CODE
	 WHERE
		ORDER_STATUS = 'Shipped'
		AND COUNTRY NOT IN ('INDIA','USA')
	 GROUP BY P.PRODUCT_ID
     ORDER BY P.PRODUCT_CLASS_CODE) AS DETAILS
GROUP BY PRODUCT_CLASS_DESC
ORDER BY TOTAL_QUANTITY DESC
LIMIT 1;
    
