-- Customers who bought more than ten (i.e. total order qty) products per shipped order

SELECT *
FROM
	(SELECT 
		OC.CUSTOMER_ID,
		CONCAT(CUSTOMER_FNAME, ' ', CUSTOMER_LNAME) AS CUSTOMER_FULLNAME,
		OH.ORDER_ID,
		SUM(PRODUCT_QUANTITY) AS TOTAL_QUANTITY	
	 FROM 
		ONLINE_CUSTOMER AS OC
		JOIN ORDER_HEADER AS OH ON OH.CUSTOMER_ID = OC.CUSTOMER_ID
		JOIN ORDER_ITEMS AS OI ON OI.ORDER_ID = OH.ORDER_ID
	 WHERE
		ORDER_STATUS = 'Shipped'
	 GROUP BY ORDER_ID) AS DETAILS
WHERE TOTAL_QUANTITY > 10;
    