-- Total quantity of products shipped for order ids > 10060

SELECT
	OI.ORDER_ID,
    OC.CUSTOMER_ID,
    CONCAT(CUSTOMER_FNAME, ' ', CUSTOMER_LNAME) AS CUSTOMER_FULLNAME,
    SUM(PRODUCT_QUANTITY) AS TOTAL_QUANTITY
FROM
	ONLINE_CUSTOMER AS OC
    JOIN ORDER_HEADER AS OH ON OH.CUSTOMER_ID = OC.CUSTOMER_ID
	JOIN ORDER_ITEMS AS OI ON OI.ORDER_ID = OH.ORDER_ID
WHERE 
	ORDER_STATUS = 'Shipped'
    AND OI.ORDER_ID > 10060
GROUP BY OH.ORDER_ID;
